version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context : ./backend
      dockerfile: Dockerfile
      no_cache: true
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/markdown_db
      - PORT=5000
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      no_cache: true
    container_name: frontend
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:

